// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.2
// source: proto/mancala/v1/game_service.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Turn int32

const (
	Turn_TURN_UNSPECIFIED Turn = 0
	Turn_TURN_PLAYER1     Turn = 1
	Turn_TURN_PLAYER2     Turn = 2
)

// Enum value maps for Turn.
var (
	Turn_name = map[int32]string{
		0: "TURN_UNSPECIFIED",
		1: "TURN_PLAYER1",
		2: "TURN_PLAYER2",
	}
	Turn_value = map[string]int32{
		"TURN_UNSPECIFIED": 0,
		"TURN_PLAYER1":     1,
		"TURN_PLAYER2":     2,
	}
)

func (x Turn) Enum() *Turn {
	p := new(Turn)
	*p = x
	return p
}

func (x Turn) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Turn) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mancala_v1_game_service_proto_enumTypes[0].Descriptor()
}

func (Turn) Type() protoreflect.EnumType {
	return &file_proto_mancala_v1_game_service_proto_enumTypes[0]
}

func (x Turn) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Turn.Descriptor instead.
func (Turn) EnumDescriptor() ([]byte, []int) {
	return file_proto_mancala_v1_game_service_proto_rawDescGZIP(), []int{0}
}

type Result int32

const (
	Result_RESULT_UNSPECIFIED  Result = 0
	Result_RESULT_PLAYER1_WINS Result = 1
	Result_RESULT_PLAYER2_WINS Result = 2
	Result_RESULT_TIE          Result = 3
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0: "RESULT_UNSPECIFIED",
		1: "RESULT_PLAYER1_WINS",
		2: "RESULT_PLAYER2_WINS",
		3: "RESULT_TIE",
	}
	Result_value = map[string]int32{
		"RESULT_UNSPECIFIED":  0,
		"RESULT_PLAYER1_WINS": 1,
		"RESULT_PLAYER2_WINS": 2,
		"RESULT_TIE":          3,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mancala_v1_game_service_proto_enumTypes[1].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_proto_mancala_v1_game_service_proto_enumTypes[1]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_proto_mancala_v1_game_service_proto_rawDescGZIP(), []int{1}
}

type FindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mancala_v1_game_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mancala_v1_game_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_proto_mancala_v1_game_service_proto_rawDescGZIP(), []int{0}
}

func (x *FindRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *FindResponse) Reset() {
	*x = FindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mancala_v1_game_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse) ProtoMessage() {}

func (x *FindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mancala_v1_game_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse.ProtoReflect.Descriptor instead.
func (*FindResponse) Descriptor() ([]byte, []int) {
	return file_proto_mancala_v1_game_service_proto_rawDescGZIP(), []int{1}
}

func (x *FindResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player1 string `protobuf:"bytes,1,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2 string `protobuf:"bytes,2,opt,name=player2,proto3" json:"player2,omitempty"`
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mancala_v1_game_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mancala_v1_game_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_mancala_v1_game_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequest) GetPlayer1() string {
	if x != nil {
		return x.Player1
	}
	return ""
}

func (x *CreateRequest) GetPlayer2() string {
	if x != nil {
		return x.Player2
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mancala_v1_game_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mancala_v1_game_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_mancala_v1_game_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type ExecutePlayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PitIndex int64  `protobuf:"varint,2,opt,name=pit_index,json=pitIndex,proto3" json:"pit_index,omitempty"`
}

func (x *ExecutePlayRequest) Reset() {
	*x = ExecutePlayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mancala_v1_game_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutePlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePlayRequest) ProtoMessage() {}

func (x *ExecutePlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mancala_v1_game_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePlayRequest.ProtoReflect.Descriptor instead.
func (*ExecutePlayRequest) Descriptor() ([]byte, []int) {
	return file_proto_mancala_v1_game_service_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutePlayRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecutePlayRequest) GetPitIndex() int64 {
	if x != nil {
		return x.PitIndex
	}
	return 0
}

type ExecutePlayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game *Game `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
}

func (x *ExecutePlayResponse) Reset() {
	*x = ExecutePlayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mancala_v1_game_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutePlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePlayResponse) ProtoMessage() {}

func (x *ExecutePlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mancala_v1_game_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePlayResponse.ProtoReflect.Descriptor instead.
func (*ExecutePlayResponse) Descriptor() ([]byte, []int) {
	return file_proto_mancala_v1_game_service_proto_rawDescGZIP(), []int{5}
}

func (x *ExecutePlayResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Side1 *BoardSide `protobuf:"bytes,2,opt,name=side1,proto3" json:"side1,omitempty"`
	Side2 *BoardSide `protobuf:"bytes,3,opt,name=side2,proto3" json:"side2,omitempty"`
}

func (x *Game) Reset() {
	*x = Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mancala_v1_game_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mancala_v1_game_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_proto_mancala_v1_game_service_proto_rawDescGZIP(), []int{6}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetSide1() *BoardSide {
	if x != nil {
		return x.Side1
	}
	return nil
}

func (x *Game) GetSide2() *BoardSide {
	if x != nil {
		return x.Side2
	}
	return nil
}

type BoardSide struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pits   []int64 `protobuf:"varint,1,rep,packed,name=pits,proto3" json:"pits,omitempty"`
	Store  int64   `protobuf:"varint,2,opt,name=store,proto3" json:"store,omitempty"`
	Player *Player `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *BoardSide) Reset() {
	*x = BoardSide{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mancala_v1_game_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoardSide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardSide) ProtoMessage() {}

func (x *BoardSide) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mancala_v1_game_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardSide.ProtoReflect.Descriptor instead.
func (*BoardSide) Descriptor() ([]byte, []int) {
	return file_proto_mancala_v1_game_service_proto_rawDescGZIP(), []int{7}
}

func (x *BoardSide) GetPits() []int64 {
	if x != nil {
		return x.Pits
	}
	return nil
}

func (x *BoardSide) GetStore() int64 {
	if x != nil {
		return x.Store
	}
	return 0
}

func (x *BoardSide) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Score int64  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mancala_v1_game_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mancala_v1_game_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_proto_mancala_v1_game_service_proto_rawDescGZIP(), []int{8}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_proto_mancala_v1_game_service_proto protoreflect.FileDescriptor

var file_proto_mancala_v1_game_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x6e, 0x63, 0x61, 0x6c, 0x61, 0x2f,
	0x76, 0x31, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x6e,
	0x63, 0x61, 0x6c, 0x61, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x3a, 0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x6e, 0x63, 0x61,
	0x6c, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65,
	0x22, 0x43, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x31, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x32, 0x22, 0x3c, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61,
	0x6e, 0x63, 0x61, 0x6c, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x67,
	0x61, 0x6d, 0x65, 0x22, 0x41, 0x0a, 0x12, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x6c,
	0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x69, 0x74,
	0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x69,
	0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x41, 0x0a, 0x13, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a,
	0x04, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x6e, 0x63, 0x61, 0x6c, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x7c, 0x0a, 0x04, 0x47, 0x61, 0x6d,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x31, 0x0a, 0x05, 0x73, 0x69, 0x64, 0x65, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x6e, 0x63, 0x61, 0x6c, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x53, 0x69, 0x64, 0x65, 0x52, 0x05, 0x73,
	0x69, 0x64, 0x65, 0x31, 0x12, 0x31, 0x0a, 0x05, 0x73, 0x69, 0x64, 0x65, 0x32, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x6e, 0x63,
	0x61, 0x6c, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x53, 0x69, 0x64, 0x65,
	0x52, 0x05, 0x73, 0x69, 0x64, 0x65, 0x32, 0x22, 0x67, 0x0a, 0x09, 0x42, 0x6f, 0x61, 0x72, 0x64,
	0x53, 0x69, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x04, 0x70, 0x69, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x30,
	0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x6e, 0x63, 0x61, 0x6c, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x22, 0x32, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x2a, 0x40, 0x0a, 0x04, 0x54, 0x75, 0x72, 0x6e, 0x12, 0x14, 0x0a, 0x10,
	0x54, 0x55, 0x52, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x55, 0x52, 0x4e, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45,
	0x52, 0x31, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x55, 0x52, 0x4e, 0x5f, 0x50, 0x4c, 0x41,
	0x59, 0x45, 0x52, 0x32, 0x10, 0x02, 0x2a, 0x62, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x53, 0x55,
	0x4c, 0x54, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x31, 0x5f, 0x57, 0x49, 0x4e, 0x53, 0x10,
	0x01, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x50, 0x4c, 0x41, 0x59,
	0x45, 0x52, 0x32, 0x5f, 0x57, 0x49, 0x4e, 0x53, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x45,
	0x53, 0x55, 0x4c, 0x54, 0x5f, 0x54, 0x49, 0x45, 0x10, 0x03, 0x32, 0xc6, 0x02, 0x0a, 0x0b, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x04, 0x46, 0x69,
	0x6e, 0x64, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x6e, 0x63, 0x61,
	0x6c, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x6e, 0x63, 0x61, 0x6c,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x12, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x67,
	0x61, 0x6d, 0x65, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x61, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x6e, 0x63,
	0x61, 0x6c, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x6e,
	0x63, 0x61, 0x6c, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x22, 0x09,
	0x2f, 0x76, 0x31, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x75, 0x0a, 0x0b,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x12, 0x24, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x6e, 0x63, 0x61, 0x6c, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x61, 0x6e, 0x63, 0x61, 0x6c,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13,
	0x32, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d,
	0x3a, 0x01, 0x2a, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x70, 0x63, 0x72, 0x69, 0x76, 0x2f, 0x6d, 0x61, 0x6e, 0x63, 0x61, 0x6c, 0x61, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x6e, 0x63, 0x61, 0x6c,
	0x61, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mancala_v1_game_service_proto_rawDescOnce sync.Once
	file_proto_mancala_v1_game_service_proto_rawDescData = file_proto_mancala_v1_game_service_proto_rawDesc
)

func file_proto_mancala_v1_game_service_proto_rawDescGZIP() []byte {
	file_proto_mancala_v1_game_service_proto_rawDescOnce.Do(func() {
		file_proto_mancala_v1_game_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mancala_v1_game_service_proto_rawDescData)
	})
	return file_proto_mancala_v1_game_service_proto_rawDescData
}

var file_proto_mancala_v1_game_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_mancala_v1_game_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_mancala_v1_game_service_proto_goTypes = []interface{}{
	(Turn)(0),                   // 0: proto.mancala.v1.Turn
	(Result)(0),                 // 1: proto.mancala.v1.Result
	(*FindRequest)(nil),         // 2: proto.mancala.v1.FindRequest
	(*FindResponse)(nil),        // 3: proto.mancala.v1.FindResponse
	(*CreateRequest)(nil),       // 4: proto.mancala.v1.CreateRequest
	(*CreateResponse)(nil),      // 5: proto.mancala.v1.CreateResponse
	(*ExecutePlayRequest)(nil),  // 6: proto.mancala.v1.ExecutePlayRequest
	(*ExecutePlayResponse)(nil), // 7: proto.mancala.v1.ExecutePlayResponse
	(*Game)(nil),                // 8: proto.mancala.v1.Game
	(*BoardSide)(nil),           // 9: proto.mancala.v1.BoardSide
	(*Player)(nil),              // 10: proto.mancala.v1.Player
}
var file_proto_mancala_v1_game_service_proto_depIdxs = []int32{
	8,  // 0: proto.mancala.v1.FindResponse.game:type_name -> proto.mancala.v1.Game
	8,  // 1: proto.mancala.v1.CreateResponse.game:type_name -> proto.mancala.v1.Game
	8,  // 2: proto.mancala.v1.ExecutePlayResponse.game:type_name -> proto.mancala.v1.Game
	9,  // 3: proto.mancala.v1.Game.side1:type_name -> proto.mancala.v1.BoardSide
	9,  // 4: proto.mancala.v1.Game.side2:type_name -> proto.mancala.v1.BoardSide
	10, // 5: proto.mancala.v1.BoardSide.player:type_name -> proto.mancala.v1.Player
	2,  // 6: proto.mancala.v1.GameService.Find:input_type -> proto.mancala.v1.FindRequest
	4,  // 7: proto.mancala.v1.GameService.Create:input_type -> proto.mancala.v1.CreateRequest
	6,  // 8: proto.mancala.v1.GameService.ExecutePlay:input_type -> proto.mancala.v1.ExecutePlayRequest
	3,  // 9: proto.mancala.v1.GameService.Find:output_type -> proto.mancala.v1.FindResponse
	5,  // 10: proto.mancala.v1.GameService.Create:output_type -> proto.mancala.v1.CreateResponse
	7,  // 11: proto.mancala.v1.GameService.ExecutePlay:output_type -> proto.mancala.v1.ExecutePlayResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_mancala_v1_game_service_proto_init() }
func file_proto_mancala_v1_game_service_proto_init() {
	if File_proto_mancala_v1_game_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_mancala_v1_game_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mancala_v1_game_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mancala_v1_game_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mancala_v1_game_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mancala_v1_game_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutePlayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mancala_v1_game_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutePlayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mancala_v1_game_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mancala_v1_game_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoardSide); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mancala_v1_game_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mancala_v1_game_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mancala_v1_game_service_proto_goTypes,
		DependencyIndexes: file_proto_mancala_v1_game_service_proto_depIdxs,
		EnumInfos:         file_proto_mancala_v1_game_service_proto_enumTypes,
		MessageInfos:      file_proto_mancala_v1_game_service_proto_msgTypes,
	}.Build()
	File_proto_mancala_v1_game_service_proto = out.File
	file_proto_mancala_v1_game_service_proto_rawDesc = nil
	file_proto_mancala_v1_game_service_proto_goTypes = nil
	file_proto_mancala_v1_game_service_proto_depIdxs = nil
}
